### ISSUE TITLE
Dockerfile `MAINTAINER` is deprecated

### ISSUE THREAD

**Issue by RobertoRoos** [opensim-org/opensim-containers#8]
See https://docs.docker.com/engine/reference/builder/#maintainer-deprecated

The `MAINTAINER` field is no longer used.

**Comment by aymanhab** [comment]
Thanks @RobertoRoos I'll fix this. Would you consider being a maintainer as well? Please let me know eitherway so I can update the scripts. Thank you

**Comment by RobertoRoos** [comment]
I'll be part of a project for a bit that uses OpenSim, hence my interest in the containers. While that's going on I can make some suggestions and contributions, but that won't be so long, sorry.

**Comment by aymanhab** [comment]
No worries, and big thanks for all your help 👍
